build: progr.c 
	gcc -Wall -std=c99 progr.c  -o myHDD
run: 
	./myHDD data.in data.out
	subl data.out
clean:
	rm  -rf myHDD

arhiva:
	zip Cotet_Teodor_Mihai_312CC_Tema1_SD.zip  *.h *.c Makefile README
